Support Kiali Iter8 monitoring dashboard
iter8-tools/iter8-trend pull request #108
Opened 2020-11-03 22:30 UTC by jadeyliu939

1. add kubernetes_namespace because of kiali changes
2. add missing app and version
    app <- service_name
    version <- winner part of the version
3. additional checking for winning. if winner is baseline, it is considered failed.
4. check if there is value in assessment[statistics]
5. add additional query iter8_trend_cpu, iter8_trend_mem, iter8_trend_custom, iter8_trend_disk, iter8_trand_network

2020-11-04 18:28 UTC, huang195 commented on iter8-trend.py
> +                    x = self.winner.split("-")
Can we rely on this naming convention to extract version?

2020-11-04 18:32 UTC, huang195 commented on iter8-trend.py
> -                            exp.winner_version = 'unknown'
I don't think this code path is active. This function is used to extract experiment CR data from prometheus. Why do we want to stop populating the winner_version field here?

2020-11-04 19:11 UTC, huang195 commented on iter8-trend.py
> +        thisLabel.append('iter8metric')
what is the difference between 'metric' and 'iter8metric"?

2020-11-04 19:15 UTC, huang195 commented on iter8-trend.py
> +                    self.doAddData( gCpu, exp, metric, False)
why is 'cpu' metric the only one called with doAddData(..., withMetric=False)?

2020-11-04 19:15 UTC, huang195 commented on iter8-trend.py
> +                    self.doAddData( gCpu, exp, metric, False)
also 'mem'

2020-11-04 19:17 UTC, huang195 commented
@jadeyliu939 I took a pass on the PR, and it looks fine except for a few questions.

2020-11-05 13:43 UTC, jadeyliu939 commented on iter8-trend.py
> +                    x = self.winner.split("-")
The original statement of find version always return "unknown" for istio 1.6 and 1.7 prometheus. Thus the changes, If there is a better way to get version, we can use it. It seems this 'version' tag is created specifically for Kiali, if this is the case. we can put the complete winner name ( for example: 'reviews-v3' ) as version.

2020-11-05 13:45 UTC, jadeyliu939 commented on iter8-trend.py
> -                            exp.winner_version = 'unknown'
This statement always result 'unknown'. It might be because the tag had changed, if there is an reliable source to get version. We can use that.

2020-11-05 13:46 UTC, jadeyliu939 commented on iter8-trend.py
> +        thisLabel.append('iter8metric')
This is needed for popular the dropdown in Kiali, if the label for iter8_trend_custom is using 'metric', the dropdown list get confused since there is another query returning the same 'metric' label.

2020-11-05 13:49 UTC, jadeyliu939 commented on iter8-trend.py
> +                    self.doAddData( gCpu, exp, metric, False)
iter8_trend_network, iter8_trend_disk and iter8_trend_custom need the metric field to form selection( or single selection). While cpu and mem only have one value for metric, so I eliminate it from the data. We can certainly put it there, since it is not being used. and just call doAddData ( without the withMetric boolean).

2020-11-05 14:36 UTC, huang195 commented on iter8-trend.py
> +                    if winner['winning_version_found'] and self.phase == 'Completed' and winner['name'] != e['status']['assessment']['baseline']['name']:
if the baseline winning doesn't count, we should get rid of the code (a few lines below) that searches for winner from the baseline.

2020-11-05 14:54 UTC, huang195 commented on iter8-trend.py
> +                    x = self.winner.split("-")
winner_app and winner_version fields were added specifically for Kiali, so it can take whatever form you think is appropriate. However, in an environment where there's no Kiali, we should make sure that the code doesn't break by making certain assumptions. I was just asking if we can assume self.winner is always in the format of `reviews-v3`. What if someone calls it `reviews-v3-test`? You might get something not as expected. If you use the entire `reviews-v3` as winner_version, and then winner_app being `review`, it would have redundancy.

2020-11-05 15:02 UTC, huang195 commented on iter8-trend.py
> -                            exp.winner_version = 'unknown'
If you search for load_data_from_prometheus, you can see this function isn't getting called. Even if we decide to re-enable this function later, it gets data from calling `data = self.query_prometheus('iter8_trend')`, and since you're making a lot of changes to the `iter8_trend` timeseries in Prometheus, I don't think the code will work anymore. My recommendation is not to touch this function and just leave it be. The changes you're making above will ensure that winner_app and winner_version are always populated

2020-11-05 15:04 UTC, huang195 commented on iter8-trend.py
> +        thisLabel.append('iter8metric')
ok

2020-11-05 15:04 UTC, huang195 commented on iter8-trend.py
> +                    self.doAddData( gCpu, exp, metric, False)
ok

2020-11-05 15:05 UTC, huang195 requested changes
looks good, just a few minor changes needed

2020-11-06 15:55 UTC, jadeyliu939 commented on iter8-trend.py
> -                            exp.winner_version = 'unknown'
Understand, I had put the part back.

2020-11-06 15:55 UTC, jadeyliu939 commented on iter8-trend.py
> +                    if winner['winning_version_found'] and self.phase == 'Completed' and winner['name'] != e['status']['assessment']['baseline']['name']:
you mean this section, right? 
```
                    # Find winner amongst baseline and candidates
                    if 'baseline' in e['status']['assessment']:
                        if 'name' in e['status']['assessment']['baseline']:
                            if e['status']['assessment']['baseline']['name'] == self.winner:
                                self.populate_winner_data(e['status']['assessment']['baseline']['criterion_assessments'])
                                self.winner_found = True
```

2020-11-06 17:26 UTC, huang195 commented on iter8-trend.py
> +                    if winner['winning_version_found'] and self.phase == 'Completed' and winner['name'] != e['status']['assessment']['baseline']['name']:
yes

2020-11-07 15:12 UTC, jadeyliu939 commented on iter8-trend.py
> +                    x = self.winner.split("-")
Adding api to get the actual version, i think this should resolve the issues of getting the correct version. 
```
try:
      deployment = self.appapi.read_namespaced_deployment(exp.winner, exp.namespace)
       if 'version' in deployment.metadata.labels:
            exp.winner_version = deployment.metadata.labels["version"]
except client.rest.ApiException as e:
       logger.info("Exception when calling AppsV1Api->read_namespaced_deployment: %s\n" % e)
```

![Screen Shot 2020-11-07 at 9 51 58 AM](https://user-images.githubusercontent.com/4615187/98444759-7bb32300-20e1-11eb-9ecf-7628576dbdfa.png)

Note: the app/winner_app is a filter to selection data related to the selected Workload. It wont be shown in the chart.

2020-11-07 15:25 UTC, jadeyliu939 commented
@huang195 
For the questionable "version", I have used the read_namespaced_deployment to get the version of deployment. But to use the `read_namespaced_deployment`, we need to add the following section in clusterrole yaml
```
- apiGroups:
  - '*'
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
```

2020-11-12 13:43 UTC, huang195 commented
@jadeyliu939 After you make the above changes to clusterole.yaml, I can merge the PR.

2020-11-13 14:32 UTC, huang195 approved these changes

2020-11-16 15:25 UTC, merged